# Generated by Django 3.0 on 2021-08-24 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210508_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
