version: "3.9"

services: 
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: >
      sh -c "python3 manage.py makemigrations && 
      python3 manage.py migrate && gunicorn --bind :8000 --workers 3 FashionPlaza.wsgi"
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
      
    depends_on: 
      - db