# Generated by Django 3.0 on 2021-05-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Cost', models.DecimalField(decimal_places=4, max_digits=5)),
                ('Company', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=10)),
                ('Subtype', models.CharField(max_length=10)),
                ('Discount', models.IntegerField()),
                ('Sale', models.BooleanField()),
                ('PrimaryImage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
