# Generated by Django 3.2.2 on 2021-05-09 15:08

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210509_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PrimaryImage',
            field=models.ImageField(upload_to=product.models.fileRename),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=product.models.fileRename),
        ),
    ]
