# Generated by Django 3.2.6 on 2021-08-21 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_size', inverse_match=True, message='Size takes only numbers coma seperated', regex='[^0-9,]')]),
        ),
    ]
